#!/bin/bash
set -e
sudo chmod 755 *
mkdir -p $HOME/bin
for filename in pr_split.py
do
    rm -f $HOME/bin/$filename
    cp $filename $HOME/bin
done

if [ -z "$(grep '$HOME/bin' $HOME/.bashrc)" ]; then
    echo 'PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
fi
